### ISSUE TITLE
Parent Issue: Setting up Your Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#62]
- [ ] How can I create an event on eventyay?
- [ ] How can I create an online event on eventyay?
- [ ] How can I create a location based or mixed online/in-person event?
- [x] Can I set up an event with multiple dates?
- [x] How to sell tickets on eventyay?
- [x] How to add additional information such as event type, links, refund policy, terms and conditions, and code of conduct?
- [x] How can I add a form to collect attendee information?
- [ ] How to add a sponsors listing to my event?
- [ ] How to add speakers and sessions settings, call for speakers and speakers form?
