### ISSUE TITLE
Parent Issue: Pricing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#64]
- [ ] How much does it cost to sell tickets on eventyay?
- [ ] How much does it cost to use eventyay for a Call for Papers or Call for Speakers?
- [ ] How and when do organizers pay for using eventyay?
- [ ] What plans are available for event organizers?

**Comment by iamdevvalecha** [comment]
How much does it cost to sell tickets on eventyay?
How much does it cost to use eventyay for a Call for Papers or Call for Speakers?
these both are already fixed.
