### ISSUE TITLE
Parent Issue: Tickets & Payments

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#65]
- [x] How do I sell tickets online?
- [x] How do I sell tickets using PayPal?
- [ ] How do I sell tickets using Stripe?
- [ ] How do I accept cheque and bank transfer for ticket payments?
- [ ] How to confirm pending orders?
- [ ] How do I accept on-site payments at the door for tickets?
- [ ] How to mark offline payments as received?
- [x] Are fees included in the ticket sales?
- [x] What currencies are supported for ticket sales?
- [ ] Can I sell tickets or allow registration on my own website using an embeddable widget?
