### ISSUE TITLE
Parent Issue: Tax & Invoices

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#66]
- [ ] Can I collect tax in my ticket sales?
- [ ] Can I issue invoices for my ticket sales?
- [ ] Can I set my company logo and billing information in receipts/invoices?
