### ISSUE TITLE
Parent Issue: Promotions & Discounts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#67]
- [ ] How to create a discount code for tickets?
- [ ] How to add an expiry date to a discount code?
- [ ] How do I apply my discount code to a ticket?

**Comment by iamdevvalecha** [comment]
this milestone is completed
