### ISSUE TITLE
Parent Issue: Cancellations & Refunds

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#68]
- [ ] How to cancel a ticket order?
- [ ] How to set a refund policy?
- [ ] How do I issue refunds?
- [ ] How do I issue refunds via PayPal?
- [ ] How do I issue refunds via Stripe?
- [ ] Can I do partial refund?
- [ ] Does eventyay charge for attendees who get a refund?
- [ ] How to cancel my event?

**Comment by mrunalvilas** [comment]
Can I work on this issue.
