### ISSUE TITLE
Parent Issue: Managing Orders & Attendees

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#69]
- [ ] How to view reports on sales and registered attendees?
- [ ] How to export and download the attendees list of my event?
- [ ] How to export and download the orders list of my event?
- [ ] How to resend confirmation emails for ticket orders?
- [ ] How to edit orders and attendee details?

**Comment by iamdevvalecha** [comment]
How to edit orders and attendee details?
starting working on this issue.

**Comment by iamdevvalecha** [comment]
How to export and download the attendees list of my event?
 How to export and download the orders list of my event?
 How to resend confirmation emails for ticket orders?
---------------------------------------------------------------------------
@mariobehling these are already fixed.

**Comment by iamdevvalecha** [comment]
milestone completed
