### ISSUE TITLE
Parent Issue: Event Roles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#71]
- [ ] How to add other organizers, moderators and volunteers to an event?
- [ ] How to control the permissions of team members?

**Comment by edenyay** [comment]
- [ ] How to transfer the ownership of an event?

**Comment by edenyay** [comment]
> * [ ]  How to transfer the ownership of an event?

this can be fixed by https://github.com/fossasia/support.eventyay.com/pull/124
