### ISSUE TITLE
Parent Issue: Speakers and Sessions Management

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#73]
- [ ] How to accept, confirm or reject a speaker submission?
- [ ] What are the different submission states such as draft, accepted, rejected, confirmed and withdrawn?
- [ ] How can I notify speakers if their session is accepted or rejected?
- [ ] What is the difference between an accepted session and a confirmed session?
- [ ] As an event organizer how can I add a speaker or session into the system?
