### ISSUE TITLE
Parent Issue: Schedule & Event Pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#74]
- [ ] How to feature speakers on the event main page?
- [ ] How to create an event schedule?
- [ ] How to schedule speakers sessions?

**Comment by iamdevvalecha** [comment]
i will work on this issue

**Comment by iamdevvalecha** [comment]
How to feature speakers on the event main page?
this is already completed.
