### ISSUE TITLE
Parent Issue: Attendees Ticketing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#76]
- [ ] How to buy tickets on eventyay?
- [ ] How to apply a discount code to your order?
- [ ] Where are my tickets?
- [ ] Do I need to print my tickets for in person events?

**Comment by Himanshunitrr** [comment]
I will like to work on this issue. What i have to do?

**Comment by iamdevvalecha** [comment]
starting working on it
