### ISSUE TITLE
Parent Issue: Attendees Refunds

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#77]
- [ ] Where to find the refund policy of an event?
- [ ] How to get a refund if I need to cancel my ticket to the event?
- [ ] How to get a refund if the organizer cancels the event?

**Comment by Hackerbone** [comment]
I would like to work on this issue but I am confused how to start! @mariobehling 
It would be really helpful if you can help me with this !

**Comment by mukul-yadavv** [comment]
@mariobehling I would like to work on this issue. Please assign this task to me.
