### ISSUE TITLE
Parent Issues: Speakers Session Submissions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#78]
- [ ] How do I submit a session?
- [ ] Where can I find my session submissions?
- [ ] How do I know if my session was accepted or rejected?
- [ ] I am no longer able to participate as a speaker at an event, how can I withdraw my submission?

**Comment by iamdevvalecha** [comment]
will start working on this!
