### ISSUE TITLE
Parent Issue: Contributors and Developers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#79]
- [x] Who develops eventyay?
- [x] What is the roadmap of the platform?
- [ ] Where can I submit a bug report or feature request?
- [x] How can I setup the system myself?
- [x] How can I contact the developers?
- [x] How can I contribute and help to improve this support site?
